import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";

const quicksand = Quicksand({
  variable: "--font-Quicksand",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jake Busse",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.variable} ${quicksand.variable}`}>
        {children}
      </body>
    </html>
  );
}
